# Generated by Django 3.1.5 on 2021-12-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='updated',
        ),
    ]
