# Generated by Django 3.1.5 on 2021-12-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemlist', '0004_auto_20211216_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='problemlist', to='problemlist.Tag'),
        ),
    ]
