# Generated by Django 3.1.5 on 2021-12-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemlist', '0006_auto_20211216_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='problem',
            name='ac_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='problem',
            name='submission_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
