# Generated by Django 3.1.5 on 2021-12-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemlist', '0007_auto_20211216_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
