# Generated by Django 3.1.5 on 2021-12-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problemlist', '0002_remove_problem_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField()),
                ('result', models.IntegerField(db_index=True, default=6)),
                ('language', models.TextField(default='C++')),
                ('info', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='submission.result')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemlist.problem')),
                ('static_info', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='submission.usage')),
            ],
        ),
    ]
