# Generated by Django 3.1.5 on 2021-12-17 03:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problemlist', '0008_auto_20211216_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField()),
                ('result', models.IntegerField(db_index=True, default=6)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('static_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('language', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemlist.problem')),
            ],
        ),
    ]
