# Generated by Django 3.1.5 on 2021-12-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='info',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='static_info',
            field=models.JSONField(),
        ),
    ]
