# Generated by Django 3.1.5 on 2021-12-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20211219_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={},
        ),
    ]
