# Generated by Django 3.1.5 on 2021-12-17 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20211217_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={},
        ),
        migrations.AlterField(
            model_name='submission',
            name='info',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='submission.result'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='static_info',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='submission.usage'),
        ),
    ]
