# Generated by Django 3.1.5 on 2021-12-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20211217_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='submission.result'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='static_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='submission.usage'),
        ),
    ]
