# Generated by Django 3.1.5 on 2021-12-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20211217_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='create_time',
            new_name='submit_time',
        ),
    ]
