# Generated by Django 3.1.5 on 2021-12-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_auto_20211217_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='space',
            new_name='memory',
        ),
    ]
